-- מבנה מסד הנתונים ב-Supabase

-- טבלת קליקים
CREATE TABLE clicks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip_address VARCHAR(45) NOT NULL,
  user_agent TEXT,
  referrer TEXT,
  page VARCHAR(255),
  gclid VARCHAR(255),
  time_on_page INTEGER,
  visit_start TIMESTAMP WITH TIME ZONE,
  event_type VARCHAR(50) DEFAULT 'pageview',
  additional_data JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- אינדקסים לטבלת קליקים
CREATE INDEX clicks_ip_address_idx ON clicks (ip_address);
CREATE INDEX clicks_gclid_idx ON clicks (gclid);
CREATE INDEX clicks_created_at_idx ON clicks (created_at);

-- טבלת כתובות IP חסומות
CREATE TABLE blocked_ips (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip_address VARCHAR(45) NOT NULL UNIQUE,
  reason TEXT,
  campaign_id VARCHAR(255),
  blocked_by VARCHAR(50) NOT NULL DEFAULT 'auto',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- אינדקס לטבלת כתובות IP חסומות
CREATE INDEX blocked_ips_ip_address_idx ON blocked_ips (ip_address);

-- טבלת כללי זיהוי
CREATE TABLE detection_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_type VARCHAR(50) NOT NULL,
  rule_value TEXT NOT NULL,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- טבלת קליקים חשודים
CREATE TABLE suspicious_clicks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip_address VARCHAR(45) NOT NULL,
  rule_id BIGINT REFERENCES detection_rules(id),
  rule_type VARCHAR(50) NOT NULL,
  click_data JSONB,
  is_blocked BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- אינדקסים לטבלת קליקים חשודים
CREATE INDEX suspicious_clicks_ip_address_idx ON suspicious_clicks (ip_address);
CREATE INDEX suspicious_clicks_created_at_idx ON suspicious_clicks (created_at);

-- טבלת נתונים מ-Google Ads
CREATE TABLE google_ads_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id VARCHAR(255),
  campaign_name TEXT,
  ad_group_id VARCHAR(255),
  ad_group_name TEXT,
  clicks INTEGER,
  impressions INTEGER,
  cost NUMERIC(10, 2),
  conversions NUMERIC(10, 2),
  date DATE,
  device VARCHAR(50),
  hour INTEGER,
  click_type VARCHAR(50),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  source VARCHAR(50) DEFAULT 'google_ads_api'
);

-- אינדקסים לטבלת נתוני Google Ads
CREATE INDEX google_ads_data_campaign_id_idx ON google_ads_data (campaign_id);
CREATE INDEX google_ads_data_date_idx ON google_ads_data (date);

-- טבלת נתוני גיאוגרפיה מ-Google Ads
CREATE TABLE google_ads_geo_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id VARCHAR(255),
  campaign_name TEXT,
  clicks INTEGER,
  cost NUMERIC(10, 2),
  date DATE,
  country_id VARCHAR(50),
  location_type VARCHAR(50),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  source VARCHAR(50) DEFAULT 'google_ads_api'
);

-- טבלת הגדרות
CREATE TABLE settings (
  id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1), -- רק רשומה אחת
  auto_block_suspicious BOOLEAN DEFAULT false,
  notification_email VARCHAR(255),
  notification_threshold INTEGER DEFAULT 5,
  google_ads_sync_interval INTEGER DEFAULT 60,
  ip_block_duration INTEGER DEFAULT 30,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- הוספת כללי זיהוי ברירת מחדל
INSERT INTO detection_rules (rule_type, rule_value, is_active) VALUES
  ('time_on_page', '5', true),
  ('multiple_clicks', '10', true),
  ('geo_location', 'RU,CN,KP', true),
  ('user_agent', 'bot,crawler,spider', true),
  ('referrer', 'empty', true);

-- הוספת הגדרות ברירת מחדל
INSERT INTO settings (
  auto_block_suspicious,
  notification_email,
  notification_threshold,
  google_ads_sync_interval,
  ip_block_duration
) VALUES (
  false,
  '',
  5,
  60,
  30
);

-- פונקציות ו-Triggers
-- עדכון שדה updated_at בטבלת הגדרות
CREATE OR REPLACE FUNCTION update_settings_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER settings_updated_at
BEFORE UPDATE ON settings
FOR EACH ROW
EXECUTE FUNCTION update_settings_updated_at();

-- עדכון שדה updated_at בטבלת כללי זיהוי
CREATE OR REPLACE FUNCTION update_detection_rules_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER detection_rules_updated_at
BEFORE UPDATE ON detection_rules
FOR EACH ROW
EXECUTE FUNCTION update_detection_rules_updated_at();

-- עדכון שדה is_blocked בטבלת קליקים חשודים כאשר ה-IP נחסם
CREATE OR REPLACE FUNCTION update_suspicious_clicks_blocked_status()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE suspicious_clicks
  SET is_blocked = true
  WHERE ip_address = NEW.ip_address;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER blocked_ip_added
AFTER INSERT ON blocked_ips
FOR EACH ROW
EXECUTE FUNCTION update_suspicious_clicks_blocked_status();